
# html lang
language: en

# main menu navigation 导航菜单显示
menu:
  Home: /
  demo: https://github.com/lizehongss/demo_show
  About: /about
  music: /
# Content 内容显示
excerpt_link: Read More
# Sidebar 侧栏分类
# sidebar 左右
widgets:
- category ##文章分类
- tagcloud ##标签 
- archives ##文章归档

# widget behavioe

show_count: true ##显示分类和归档文章数目
archive_type: monthly  ##归档类型yearly or monthly


# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/zhl.css ## 自定义样式，会覆盖 

# scripts loaded in the end of the body
scripts:
- /js/zhl.js 
- /js/bj.js ##背景动画
